### ISSUE TITLE
Add ability to generate a property directive in Visual Studio

### ISSUE THREAD

**Issue by benquarmby** [benquarmby/jslintnet#14]
JSLint generates a property directive whenever it is run over a script. Add a context menu item to JSLint.NET for Visual Studio to automatically insert or update this directive with properties from the current file.

**Comment by M0nter0** [comment]
I'm using v 2.2.0.0 and I can't see the option in the context menu referenced in [Release notes v.2.1.0](https://github.com/benquarmby/jslintnet/releases/tag/v2.1.0) `Generate Property Directive`:
When I left click a file, I just have:
- Run JsLint
- Ignore file

Am I losing something? Changes referenced in [Release notes v.2.2.0](https://github.com/benquarmby/jslintnet/releases/tag/v2.2.0) are working fine.

**Comment by benquarmby** [comment]
Short answer: Open the file and right click in the text editor to see the new context menu item.

Because JSLint.NET is actually altering files when it generates a property directive, it has to be very careful about not making destructive on unintentional changes. For now, it does this by requiring that the file is open so that the change can be seen and undone if necessary.

This is also in keeping with the spirit of the JSLint property directive, which is designed to show intent. It's basically saying, "these are the properties I specifically intended to use." If there isn't any human interaction and it's fully automated, then there is also no intent.

So for now JSLint.NET generates property directives interactively in a semi-automatic way, the same as http://www.jslint.com/.

**Comment by benquarmby** [comment]
The release notes have been clarified to state that the new context menu item is in the code editor.

**Comment by M0nter0** [comment]
I got it, @benquarmby Thanks!
