### ISSUE TITLE
Add compatibility for Visual Studio 2015 for Web

### ISSUE THREAD

**Issue by richardtallent** [benquarmby/jslintnet#15]
I received this error on installation:

```
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```

I'm using Visual Studio 2015 for Web, and it would be a great fit for this sort of extension, if possible.

**Comment by benquarmby** [comment]
You're absolutely right. It would be a great fit and should totally work in that environment. I'll investigate.

**Comment by benquarmby** [comment]
@richardtallent I'm having a hard time finding Visual Studio 2015 for Web. Do you mean VS2015 Express for Web? If so, to the best of my knowledge extensions are not supported in any Express editions.

However, I would recommend using the [NuGet package](https://www.nuget.org/packages/JSLintNet.MSBuild/) which should work fine.

Or you could switch to VS2015 Community edition which is the equivalent of Professional edition and should allow extensions. If it doesn't work there, please let me know.

**Comment by richardtallent** [comment]
Yes, I was referring to VS 2015 Express for Web. It has some pre-installed extensions, so it must support them to some degree, but I don't know what the limitations are.

I use Community Edition at home for personal projects, but I can't use it at work (license limitation).

However, I _can_ use Visual Studio Code at work, and I've been able to install another linter, ESLint, in that one. So that may be my best option until my employer sets me up with a paid edition of VS 2015.
