### ISSUE TITLE
Bad property name on angularjs property/methods

### ISSUE THREAD

**Issue by matteo-mosca** [benquarmby/jslintnet#16]
I am using angularjs along with jslint.net in my aspnet application.

When using angularjs stuff like "$watch", "$inject", "$promise", etc I get the jslint error "Bad property name". Since I am using warnings as errors this is preventing me to compile the project.

Since angularjs is built this way and I'm perfectly fine with this there should be a way to turn this validation off, as we can turn off other validations, using the json file.

This problem is forcing me to downgrade to v 1.8.

**Comment by benquarmby** [comment]
You're definitely not the first to run into this issue with the Angular APIs. See issue #12 for a previous response. You may also find unused arguments in callback signatures difficult with the latest JSLint.

There is work under way on a property directive generator (#14), which should help with bad property names in the near future.

**Comment by benquarmby** [comment]
The property directive generator is now available in JSLint.NET for Visual Studio v2.1.0. I hope it helps.

**Comment by matteo-mosca** [comment]
Alas it does not help. If I add the /\* property */ block then I need to declare every single property used in the file, not just the ones that were raising an error, generating more errors than before.

Isn't there a way to disable the "bad property name" feature like we do with other stuff, like the "tolerate this" or similar?

**Comment by benquarmby** [comment]
Unfortunately not. However the property directive generator in 2.1.0 will scan and repopulate that block at the click of a button. All the properties from the current file will be included. So at least you don't have to maintain it by hand.

**Comment by matteo-mosca** [comment]
So, where is this automated function? I installed the nuget package (jslint msbuild) and I don't see anything like that. Do I require the vs2015 tool too? In this case the plugin would become a project dependency, and I don't like this idea. The project should depend only on the nuget packages.

**Comment by benquarmby** [comment]
I completely agree. NuGet is the ideal way to distribute dependencies like this. Then there isn't any need to roll out IDE extensions and make sure everyone has the right version, etc.

But unfortunately this functionality is only possible via JSLint.NET for Visual Studio, since it needs access to open, editable files. The two (NuGet and VSIX) can run side by side comfortably, but I can understand if that overhead is too much.

**Comment by ssg** [comment]
Is there way to disable "Bad property name" checks completely from configuration JSON? I see nothing in the documentation regarding this, including JSLint's. There are A LOT of properties I need to add otherwise.

**Comment by benquarmby** [comment]
@ssg: Not that I know of. It appears to be by design.
