### ISSUE TITLE
Error when running with MsBuild

### ISSUE THREAD

**Issue by matteo-mosca** [benquarmby/jslintnet#17]
I am trying to compile my web project using MsBuild on a build server, and I am costantly getting this error:

error MSB4018: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\v8-x64.dll: The specified module could not be found

The strange thing is that it shouldn't be looking for the clearscript library in that path, but in the JsLint.Net package path, where it is correctly located:

{{solutiondir}}\packages\JSLintNet.MSBuild.2.0.4\tools

The same project compiled with VS2015 works fine.

**Comment by benquarmby** [comment]
Does this also happen with 1.8.x?

Edit: I ask because you mentioned you downgraded in another issue.

**Comment by matteo-mosca** [comment]
Yes, it happens on 1.8.x as well.

**Comment by benquarmby** [comment]
A couple of follow up questions:
- Which version of Visual Studio is installed on the build machine if any?
- Do you know if the Visual C++ 2012 redistributable is installed?

**Comment by matteo-mosca** [comment]
The build machine does not have VS installed, just the required SDKs.
I have installed VS 2015 and 2013 C++ redis but not the 2012 one. I will
try, though I don't see how it can fix the wrong path problem.

**Comment by benquarmby** [comment]
I know what you mean. The path error seems to zero in on the issue pretty directly. But I've found that problems with the VC++ dependencies often result in misdirected errors.

**Comment by benquarmby** [comment]
How did you go?

If installing the VC++ redistributable worked, I'll transition this issue to a documentation issue. I clearly haven't clarified the pre-requisites!

If it didn't work, I'll build up an environment to match yours and see if I can replicate the problem.

Either way, please keep me up to date.

**Comment by matteo-mosca** [comment]
I installed the 2012 VC++ and the problem went away. If I have more trouble about this I will reopen the issue.

Thanks.
