### ISSUE TITLE
JSLint.net 2.1.0 does not ignore jslint warning/error messages results in files/folders.

### ISSUE THREAD

**Issue by wpostma** [benquarmby/jslintnet#19]
**Neither file scope "ignore file" or folder scope "ignore folder" items are working in JSLint.net 2.1.0.**

For example, in an ExtJS codebase, I have configured ignore-folder for a folder containing some javascript files that are auto-generated by a remote-procedure-invocation tool.  I am not going to go and remove all spurious semicolons or re-format the tool-generated code.  If I could figure out how to emit an "/\* ignoreme */" comment that could be respected by JSLint itself, that would be cool, but I currently don't know how to do that.

What would be great is if JSLint.net would just let JSLint do what it wants and then post-processing (after JSLINT itself reports errors) have it just not output into visual studio errors/warnings list the items where the file name is in the "ignored" file or folder set.

If this is a known issue and requires someone to work on it to implement it, I would be willing to try to implement it, make a fork and issue a pull request. (I'm not asking the author to spend his limited time fixing this if it only helps me, I'd be happy to try to fix it.)

It's also possible that (due to my newness to JSLint.net) I'm missing something obvious, or some obvious workaround or something.

My JSLint.net.json:

```
        {
        "version": "2.1.0",
        "output": "Warning",
        "ignore": [
            "indent",
            "no-extra-parens",
            "\\common\\src\\webservice\\dicomservice_Intf.js",
            "\\common\\src\\webservice\\DictationLibrary_Intf.js",
            "\\common\\src\\webservice\\emaildistribution_Intf.js",
            "\\common\\src\\webservice\\ImageSource_Intf.js",
            "\\common\\src\\webservice\\MobilePortal_Intf.js",
            "\\common\\src\\webservice\\PowerReader_Intf.js",
            "\\common\\src\\webservice\\PowerReaderCache_Intf.js",
            "\\common\\src\\webservice\\PowerReaderRODLTypes_Intf.js",
            "\\common\\src\\webservice\\prcacheroservice_Intf.js",
            "\\common\\src\\webservice\\Priority_Intf.js",
            "\\common\\src\\webservice\\reportinfo_Intf.js",
            "\\common\\src\\webservice\\RSAccessManagement_Intf.js",
            "\\common\\src\\webservice\\RSCommonTypes_Intf.js",
            "\\common\\src\\webservice\\RSDataSnapModule_Intf.js",
            "\\common\\src\\webservice\\RSDicomTypes_Intf.js",
            "\\common\\src\\webservice\\rulesbasedsystem_Intf.js",
            "\\common\\src\\webservice\\scheduler_Intf.js",
            "\\common\\src\\webservice\\studybookmark_Intf.js",
            "\\common\\src\\webservice\\viewerstorage_Intf.js",
            "\\common\\src\\webservice\\VolumeConfig_Intf.js",
            "\\common\\src\\webservice\\WADOLibrary_Intf.js",
            "\\common\\src\\webservice\\WebLibrary_Intf.js",
            "\\common\\src\\webservice\\Worklist_Intf.js",
            "\\common\\src\\webservice\\reportdistribution_Intf.js",
            "\\common\\src\\webservice\\"
        ],
        "options": {
            "browser": true,
            "for": true,
            "node": true,
            "this": true,
            "white": true
        },
        "globalVariables": [
            "Ext",
            "navigator",
            "Common",
            "RapidResults"
        ],
        "errorLimit": 999,
        "fileLimit": 999
        }
```

**Comment by benquarmby** [comment]
You are not missing anything. Ignoring a directory of generated code is a perfect example of what those ignore rules are supposed to be for.

Outside in, your settings file looks fine. Technically you should only need "\common\src\webservice\", and all children of that folder should be ignored. This assumes that common\src\webservice is in the root of your project (adjacent to JSLintNet.json).

At first glance this looks like a bug with JSLint.NET. Would you mind answering a couple of questions to help me diagnose?
- Is your project a website or a web app? (the later has .csproj / .vbproj file)
- Are you using a shared (linked) JSLintNet.json file?
- Did you setup the ignore rules using JSLint.NET for Visual Studio (right click folder, "Ignore Folder")? If not, can you try that please?

![image](https://cloud.githubusercontent.com/assets/1434816/12567009/e977aef2-c410-11e5-82b8-446eb2cb40de.png)

**Comment by wpostma** [comment]
I used ignore folder menu item. I will put a demo project with .csproj (its a webapp not web project) online tomorrow.

**Comment by benquarmby** [comment]
Thank you, a repro will help a lot!

**Comment by benquarmby** [comment]
Please do post a demo project @wpostma. I want to get to the bottom of this issue if I can.

**Comment by benquarmby** [comment]
I will close this issue for now. Please re-open if you are able to post a repro.
