### ISSUE TITLE
JS Lint Build Errors

### ISSUE THREAD

**Issue by Sumits669** [benquarmby/jslintnet#21]
Hi ,

I have configure jslint from nuget manager in my visual studio 2013 and plateform is Windows server 2008 R2.
When I build solution then it shows an error while I converted all errors type into warnings and due to this error build is faild.
Error is : "Build canclled due to JSlint validation errors".
How can I resolve this so that i can see all errors only in warning, while all errors converted to warnings but still one error i got.
Please suggest me how can i resolve this

**Comment by benquarmby** [comment]
Uncheck "Cancel build" in the project settings. If you're running both JSLint.NET for Visual Studio and JSLint.NET for MSBuild (from NuGet), you can also uncheck the "Run on build" checkbox.

![image](https://cloud.githubusercontent.com/assets/1434816/12775494/b6eb3eb6-caa2-11e5-86d6-a583330e6f1a.png)

I may remove both of these checkboxes in the future to save confusion. The MSBuild task _always_ runs on build regardless of this setting.

**Comment by benquarmby** [comment]
I added issue #23 to track removing those settings.
