### ISSUE TITLE
JSLint : Expected 'new' and instead saw '.'.

### ISSUE THREAD

**Issue by MJaz08** [benquarmby/jslintnet#26]
I am getting this error with the 2.2.1.0 version.
I see this post http://www.simosh.com/article/dgbdbeif-jslint-expected-new-and-instead-saw.html talking about a fix that was added by Crockford.
can you please update the VS extension.

**Comment by benquarmby** [comment]
Yes, I can see the Date.UTC edge case has been patched recently. Will update JSLint.NET.

**Comment by benquarmby** [comment]
Fixed in 2.2.2.

**Comment by MJaz08** [comment]
Thank you for the prompt response. Is there a way for me for download the older version of the visual studio extension? I am looking for : JSLintNet.VisualStudio.2.0.3.vsix  
We have a lot of work to do before we can move to the latest version for one our projects and it will be helpful if we are able to install JSLintNet.VisualStudio.2.0.3.vsix
Thanks

**Comment by benquarmby** [comment]
@MJaz08: If you don't mind me asking, what is the change between 2.0.3 and the latest version that's causing problems? Is it the "multivar" change? Or something to do with capitalized functions?

**Comment by MJaz08** [comment]
We are getting Expected 'new' and instead saw '.' errors because of The capitalized functions. It was not an issue with 2.0.3

**Comment by MJaz08** [comment]
We are getting Expected 'new' and instead saw '.' errors because of The capitalized functions. It was not an issue with 2.0.3

**Comment by benquarmby** [comment]
Since the Visual Studio gallery doesn't keep historical versions, I have added the VSIX binary to the 2.0.3 release here on GitHub:
https://github.com/benquarmby/jslintnet/releases/tag/v2.0.3

The NuGet package however is easily accessible here:
https://www.nuget.org/packages/JSLintNet.MSBuild/2.0.3

**Comment by MJaz08** [comment]
Thank you!
