### ISSUE TITLE
Documentation missing on how to ignore specific numerical errors in configuration JSON

### ISSUE THREAD

**Issue by ssg** [benquarmby/jslintnet#36]
I have been trying to disable warnings like "W068" in several ways and failed to do so. Documentation on configuration JSON doesn't explain how these work. There is a link provided with "special option syntax" but the target page doesn't explain this special option syntax either.

**Comment by benquarmby** [comment]
I do not know what W068 is or how to disable it. Are you sure it's coming from JSLint.NET?

**Comment by ssg** [comment]
It's this warning: https://github.com/jamesallardice/jslint-error-explanations/blob/master/message-articles/unnecessary-function-parens.md

**Comment by ssg** [comment]
It would actually be great if JSLint.NET had provided the option name next to the error message (like how ESLint on VS2017 does).

**Comment by benquarmby** [comment]
Where ESLint is completely configurable, JSLint has almost no configuration. They are philosophically very different. You will not find a way to turn individual rules on or off in JSLint. That's a design choice by the author, Douglas Crockford. It asks that the code author trust the tool and give up on individual style. Complying with JSLint's rules with third party libraries is non-trivial - bad property names and callback signatures come to mind. One technique I've seen is to wrap the offending code in a facade without the code smells.

Edit: Just in case I wasn't explicit, you will not find a way to disable individual rules. No such thing exists in JSLint. Let me save you any more time looking for it.

**Comment by ssg** [comment]
I'll have to use ESLint (or JSHint) then. I appreciate your explanation in detail Ben, thanks.

**Comment by benquarmby** [comment]
Full disclosure, the main product I currently work with is built with JSX. JSLint is unlikely to ever support JSX, so I use ESLint in its place. That said, JSLint's ruleset is the safest and most logical I've personally come across, so I've tuned ESLint to mirror it as closely as possible.

I would not recommend JSHint. It is a fork of JSLint that turned into a giant mess of confusing switches and options. The worst of both worlds.

**Comment by ssg** [comment]
Thanks! I totally understand that but that makes it almost impossible to incorporate it later in a large project and gradually adopt the standards over time.
