### ISSUE TITLE
Not compatible with Cordova projects?

### ISSUE THREAD

**Issue by quilkin** [benquarmby/jslintnet#7]
I have been using JSLint for a while in javascript projects edited with VS2013. But I am now experimenting with the  Cordova plugins for VS2013 (and later VS2015), and JSLint won't run with any of the .js files in the project. I get the error message "The directory name [project path]\mymap.jsproj is invalid". But 'mymap.jsproj' isn't a directory, it's the VS project definition file.

However if I load a .js file that's not part of the project into the same IDE, jslint runs on that OK. It also runs OK on a javascript project that isn't based on Cordova.

It's not a problem with my particular project setup; the same issue occurs with a simple 'empty' project created by VS.

**Comment by benquarmby** [comment]
Thanks for the report. I'll look into it.

**Comment by jmatthiesen** [comment]
@benquarmby - feel free to ping me if you have questions about the Cordova project configuration in Visual Studio. I'm a member of the Visual Studio team that works on this project type.

**Comment by benquarmby** [comment]
@jmatthiesen Thank you, I'll probably take you up on that. At this point I believe the problem is related to finding the project root directory. I'll test that theory and come back if I need any more help.

**Comment by benquarmby** [comment]
The fix is in master and will be rolled into a stable release soon. It's also in the beta release today.

**Comment by quilkin** [comment]
Ben, that's great, many thanks. Just installed the beta and it's working fine with my Cordova project.
Regards Chris
